### ISSUE TITLE
Outline doesn't work with CHAR animation

### ISSUE THREAD

**Issue by Helvest** [Luca3317/TMPEffects#18]
**Describe the bug**
When a TMP text has an outline that enlarges the letter triangles, this size is ignored by the CHAR animation, incorrectly displaying the outline.

**To Reproduce**
1. Create a GameObject with a Text Mesh Pro component.
2. Set a text starting with <char>.
3. Set the text material outline parameter to 1.

**Expected behavior**
An outline not cut by the incorrect vertex sizes.

**Comment by Luca3317** [comment]
Hey, should be fixed with 070dd51

**Comment by Helvest** [comment]
Yes, it work now, thank you
