### ISSUE TITLE
Cannot get tag <+grow startscale=...> to work

### ISSUE THREAD

**Issue by maarten-abbey** [Luca3317/TMPEffects#19]
**Describe the bug**
I'm trying to use the tag `<+grow startscale=10.0>`. There is no exact syntax example in the docs, but this is what I assumed should work, based on the syntax for 'normal animations' and how they handle parameters.

**To Reproduce**
Add the tag `<+grow startscale=10.0>`, either at the start of a text or as a "default show animation" override. In the former case, the tag is not parsed and rendered as text instead. In the latter case, I get a triangle with "Parameters are not valid for this tag".

**Expected behavior**
I expect the start size to change, but instead the tag is not parsed.

**Screenshots**
![image](https://github.com/user-attachments/assets/03f65cbf-2147-4fd3-97c6-0230d05cb8e5)
![image](https://github.com/user-attachments/assets/32ce40b1-da4d-43c9-9476-2658e11d8e76)
![image](https://github.com/user-attachments/assets/625884b4-1d85-462c-b5df-e8f8378c26e9)

**Additional context**
Maybe I just don't understand the syntax. I couldn't find an example in the docs, though.

**Comment by Luca3317** [comment]
grow's startscale is a Vector2/3, so in your case you would do `<+grow startscale=(10,10)>`.

I should probably add the types of each parameter to the docs.
For now you can check the animation's ScriptableObject (or its script) for the type. The tooltip also gives you all its aliases.
Here's also an overview of each parameter type and how to format them in the animation tag:
https://tmpeffects.luca3317.dev/docs/parametertypes.html

**Comment by maarten-abbey** [comment]
Got it, thanks!
