### ISSUE TITLE
Unable to view the docs.

### ISSUE THREAD

**Issue by CodeRedStudio** [Luca3317/TMPEffects#31]
I keep click the documentation link and it basically 404's. It would be awesome if you could help with this.

**Comment by Luca3317** [comment]
Hey, yeah sorry Im reworking the docs right now because Im about to merge a branch with a bunch of changes.
I assumed that was not gonna take long so I didnt bother keeping the old docs up. Ill fix that.

**Comment by CodeRedStudio** [comment]
Thanks, mate!
